 // Source code is unavailable, and was generated by the Fernflower decompiler.
 package edu.cmu.cs.cs214.rec04;

 import java.util.ArrayList;
 import java.util.Comparator;
 
 public class SortedIntList implements IntegerList {
    private ArrayList<Integer> sortedList = new ArrayList();
 
    public boolean add(int num) {
       Integer in = new Integer(num);
       boolean success = this.sortedList.add(in);
       this.sortedList.sort((Comparator)null);
       return success;
    }
 
    public boolean addAll(IntegerList list) {
       boolean success = true;
 
       for(int i = 0; i < list.size(); ++i) {
          success &= this.add(list.get(i));
       }
 
       this.sortedList.sort((Comparator)null);
       return success;
    }
 
    public int get(int index) {
       return (Integer)this.sortedList.get(index);
    }
 
    public boolean remove(int num) {
       boolean success = this.sortedList.remove(new Integer(num));
       this.sortedList.sort((Comparator)null);
       return success;
    }
 
    public boolean removeAll(IntegerList list) {
       boolean success = true;
 
       for(int i = 0; i < list.size(); ++i) {
          success &= this.remove(new Integer(list.get(i)));
       }
 
       this.sortedList.sort((Comparator)null);
       return success;
    }
 
    public int size() {
       return this.sortedList.size();
    }
 }
 